### ISSUE TITLE
File names with multiple dots are problematic

### ISSUE THREAD

**Issue by calebwherry** [Korovasoft/Regional#10]
Because of the way that file names are handled, if one is encountered with multiple dots in the name, python throws up.

This is because SOMEONE decided to use the split function instead of using the Path.split() function which takes care of this case. When getting basename, ext, and filename, a Path variable should always be created from the string filename and then acted upon by the Path functions. Much better handling of files that way.

**Comment by robertdfrench** [comment]
Sounds good, I thought I had fixed this though. Or at least I intended to. But if there is a proper Path class then that's definitely better than whatever half-ass regex I cook up.
